### ISSUE TITLE
The shape of pre-trained model does not match the model defined in ‘default.py’

### ISSUE THREAD

**Issue by JinxVision** [intel-isl/DeepLagrangianFluids#1]
Hello, I am very interested in this exciting work. I tried to run the inference code. However, I met some problem. The shape of pre-trained model does not match the model defined in ‘default.py’. Could you please provide the 'default.py'  that matches the pre-trained parameters ?

**Comment by benjaminum** [comment]
Hi, there seems to be a problem with the weights loading but so far I was not able to reproduce it.
Can you try to change the following line
https://github.com/intel-isl/DeepLagrangianFluids/blob/21ddc4e05af4469e498d585c952a09c4688ae678/scripts/run_network.py#L42
to 
```python
    model.load_weights(weights_path, by_name=True)
```
Can you tell me which Tensorflow version you use?

**Comment by JinxVision** [comment]
> Hi, there seems to be a problem with the weights loading but so far I was not able to reproduce it.
> Can you try to change the following line
> https://github.com/intel-isl/DeepLagrangianFluids/blob/21ddc4e05af4469e498d585c952a09c4688ae678/scripts/run_network.py#L42
> 
> 
> to
> ```python
>     model.load_weights(weights_path, by_name=True)
> ```
> 
> Can you tell me which Tensorflow version you use?

It works for me! The version of tf is 2.0.0.

**Comment by benjaminum** [comment]
f55ac60 now loads the weights by name. Please reopen if there are still problems.
