### ISSUE TITLE
A question about the comparison of efficiency between cconv and traditional PBF

### ISSUE THREAD

**Issue by W-Alex-Y** [intel-isl/DeepLagrangianFluids#10]
Excellent work!
But I didn't find the comparision of efficiency between PBF and ur approach(cconv) in this paper.
So I just wonder if ur approach runs much more faster than traditional PBF in the simulation of same scenes.
Thx a lot！

**Comment by benjaminum** [comment]
Hi, 
the runtime is not better than PBF. The original PBF paper reports about 10ms per frame for 128k particles. With the inference script in this repo you can simulate in real-time about 20k particles (20ms per frame). 
The inference script is meant to be easy to use and not optimized for speed but even with optimizations it would still be slower because PBF is a simpler algorithm. Our network approximates DFSPH which is a more accurate algorithm than PBF.
Another difference to PBF is that our method is trained to simulate liquids. With the right data it could be trained to simulate something else.
I hope this answers your question.

**Comment by W-Alex-Y** [comment]
> Hi,
> the runtime is not better than PBF. The original PBF paper reports about 10ms per frame for 128k particles. With the inference script in this repo you can simulate in real-time about 20k particles (20ms per frame).
> The inference script is meant to be easy to use and not optimized for speed but even with optimizations it would still be slower because PBF is a simpler algorithm. Our network approximates DFSPH which is a more accurate algorithm than PBF.
> Another difference to PBF is that our method is trained to simulate liquids. With the right data it could be trained to simulate something else.
> I hope this answers your question.

Thank u for ur reply!
I got 2 new questions.

1. I read the **DFSPH paper** and found that DFSPH has a better performance and runs faster than PBF in most scenes.
2. Why did ur error become **large at the beginning** and then **automatically become much less** after 200 frames in **Figure 6**? How could it happen? I am a little confused about it.

Hope u have a nice day!

**Comment by benjaminum** [comment]
1. I think the DFSPH solver is good especially for large time steps. The PBF solver probably requires more iterations in this setting which makes it slower.

2. The beginning of the sequence is most chaotic because the fluid splashes against the scene boundary. Because of the chaotic behavior the errors are larger.

**Comment by W-Alex-Y** [comment]
> * I think the DFSPH solver is good especially for large time steps. The PBF solver probably requires more iterations in this setting which makes it slower.
> * The beginning of the sequence is most chaotic because the fluid splashes against the scene boundary. Because of the chaotic behavior the errors are larger.

Thx a lot!

**Comment by W-Alex-Y** [comment]
> 1. I think the DFSPH solver is good especially for large time steps. The PBF solver probably requires more iterations in this setting which makes it slower.
> 2. The beginning of the sequence is most chaotic because the fluid splashes against the scene boundary. Because of the chaotic behavior the errors are larger.

Thx a lot!
So what are the **advantages** of cconv over DFSPH or PBF for simulating fluid? 
Can we use cconv to **speed up** the traditional simulation methods?

**Comment by benjaminum** [comment]
- The advantage is that you can build a system that can be trained from data with cconvs. DFSPH and PBF are algorithms that are fixed.
- Yes

**Comment by W-Alex-Y** [comment]
> * The advantage is that you can build a system that can be trained from data with cconvs. DFSPH and PBF are algorithms that are fixed.
> * Yes

Thx for ur reply.
As u said before, it's slower than PBF. So how can I accelerate PBF by using cconvs?
Apparently the NNS is the most time-consuming part of PBF algorithm. And the cconvs still need the neighbor particles information to predict the particle motion at the next time step.
I'm a little confused about it, hope u can help me.
Best wishes.

**Comment by benjaminum** [comment]
It depends on the speed quality trade-off you want to make. In the PBF paper speed is preferred. For better quality, usually more solver iterations or smaller time steps are needed which make the methods run slower.
You are right about the neighbor search. All the algorithms need to compute this information.

**Comment by W-Alex-Y** [comment]
> It depends on the speed quality trade-off you want to make. In the PBF paper speed is preferred. For better quality, usually more solver iterations or smaller time steps are needed which make the methods run slower.
> You are right about the neighbor search. All the algorithms need to compute this information.

Got it. Thx!
