### ISSUE TITLE
importerror when run the example pretrained network

### ISSUE THREAD

**Issue by hanlinGao** [intel-isl/DeepLagrangianFluids#12]
I got an error saying
`ImportError: /home/xxx/FluidCC/MY_ENV/lib/python3.7/site-packages/open3d/cpu/pybind.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNSt3__119__shared_weak_countD2Ev`
when run the example
`./run_network.py --weights pretrained_model_weights.h5 \
>                  --scene example_scene.json \
>                  --output example_out \
>                  --write-ply \
>                  train_network_tf.py
`
I have added the path where the .so file is installed into the LD_LIBRARY_PATH and restarted bash, but it still has this error.
So I think it might be a problem when building the .so file, but I have no idea what problem cause this error.

The build log shows I only have three things that are skipped:

- Performing Test CMAKE_HAVE_LIBC_PTHREAD - FAILED
- Could not find Vulkan
- Check the size of off64_t failed

I am running on Ubuntu 20.04 and use a cpu version of tensorflow 2.0 with python3.7 in my virtual environment.
Could you give me some suggestion?

**Comment by benjaminum** [comment]
Adding the .so to the LD_LIBRARY_PATH should not be necessary for open3d. Do you get the same error without adding to LD_LIBRARY_PATH? Can you try to just import open3d?
```python
import open3d
```

**Comment by hanlinGao** [comment]
> Adding the .so to the LD_LIBRARY_PATH should not be necessary for open3d. Do you get the same error without adding to LD_LIBRARY_PATH? Can you try to just import open3d?
> 
> ```python
> import open3d
> ```

yep, I gain the same error without adding to LD_LIBRARY_PATH and just import open3d
`ImportError: /home/xxx/FluidCC/MY_ENV/lib/python3.7/site-packages/open3d/cpu/pybind.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNSt3__119__shared_weak_countD2Ev`

It seems like the .so file I built lack something? but how to figure what part I miss?

**Comment by benjaminum** [comment]
The problem seems to be specific to Open3D. Can you open a new issue for Open3D https://github.com/intel-isl/Open3D ?

**Comment by hanlinGao** [comment]
> The problem seems to be specific to Open3D. Can you open a new issue for Open3D https://github.com/intel-isl/Open3D ?

Sure. Thanks anyway~
