### ISSUE TITLE
Is there any description about the dataset?

### ISSUE THREAD

**Issue by hanlinGao** [intel-isl/DeepLagrangianFluids#13]
Hi, I downloaded the dataset, but it could not be decoded with one `msgpack.loads`. It seems that there are lots of things need to be decoded, like keys of the dictionary are binary string and pos values are bytes and I don't know the way it was encoded.
Do you have any suggestion on it?

Thank you!

**Comment by benjaminum** [comment]
Hi, you can find the code for decoding here https://github.com/intel-isl/DeepLagrangianFluids/blob/51e5b74d4fe4ca5e837e5f789432585a2b1e6ffc/datasets/dataset_reader_physics.py#L37

Make sure you have `msgpack_numpy` installed and that you call the patch function to get numpy arrays during decode.
```python
import msgpack
import msgpack_numpy
msgpack_numpy.patch()
```

**Comment by hanlinGao** [comment]
Thank you very much!
