### ISSUE TITLE
MapInvert in scene.json not set to TRUE and the scene has abnormal behavior

### ISSUE THREAD

**Issue by ChloeZPan** [intel-isl/DeepLagrangianFluids#14]
Hi,

I used the ./create_data.sh to generate training and testing sets. However, when I rendered the scene.json in the splishsplash, it acts abnormally. Compared to DamBreak files, it does not set MapInvert to TRUE. I am wondering if the true training sets are like this or not.

Thank you!

Zeyi

**Comment by benjaminum** [comment]
Hi,
You can find the link to the original training data in the readme https://github.com/intel-isl/DeepLagrangianFluids#data-download to compare to.
Make sure to use SPlisHSPlasH 2.4.0 when you generate data. SPlisHSPlasH is developing and maybe MapInvert is a new parameter.

**Comment by ChloeZPan** [comment]
Thank you!
