### ISSUE TITLE
Questions about boundary particle in run_network.py

### ISSUE THREAD

**Issue by hanlinGao** [intel-isl/DeepLagrangianFluids#15]
I find you use 1.9 * S(obj) / S(particle) to roughly match the number of boundary particles, can I ask about why don't you use directly the boundary particle output from SPlisHSPlasH's surface sampling?
I mean you use the volume sampling of it to generate fluid particles, but give up the surface sampling to generate boundary particles, which will introduce a new variable. For example, if I want to compare the performance between pretrained model and the ground truth that is generated by SPlisHSPlasH, I will hope they have the same initial fluid particles and boundary particles. But now they have different boundary particles.

**Comment by benjaminum** [comment]
The idea here is to reduce dependencies. The goal is to be able to run the network without SPlisHSPlasH. Unfortunately, the volume sampling-as you mentioned-still relies on it and I did not have time yet to reimplement this functionality.

**Comment by hanlinGao** [comment]
Thanks, so if I want to compare the performance of the model and the ground truth, I'd better input the particles generated in the model into the SPlisHSPlasH... 
Thanks!
