### ISSUE TITLE
*.msgpack.zst': No such file or directory

### ISSUE THREAD

**Issue by GUT2060** [intel-isl/DeepLagrangianFluids#16]
Hi 
After running The data generation script in the datasets subfolder : ./create_data.sh , i get the following error for all sim__ folders generated under our_defautl_scenes : 
mv: cannot stat 'ours_default_data/sim__*.msgpack.zst': No such file or directory   
This leads to an empty valid and train folders under our_default_data .
any guide line on how to solve this would be great 

Thanks

**Comment by GUT2060** [comment]
running the create_physics_records.py seperatly i get the following error : 
sim_0001
Traceback (most recent call last):
  File "*****/env36/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 765, in array_split
    Ntotal = ary.shape[axis]
AttributeError: 'NoneType' object has no attribute 'shape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "create_physics_records.py", line 148, in <module>
    main()
  File "create_physics_records.py", line 144, in main
    create_scene_files(scene_dir, scene_name, outfileprefix, args.splits)
  File "create_physics_records.py", line 38, in create_scene_files
    sublists = np.array_split(frames, splits)
  File "<__array_function__ internals>", line 6, in array_split
  File "****/env36/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 767, in array_split
    Ntotal = len(ary)
TypeError: object of type 'NoneType' has no len()

**Comment by benjaminum** [comment]
Hi @GUT2060 , can you check that you have SPlisHSPlasH 2.4.0 installed?

**Comment by GUT2060** [comment]
Hi , @benjaminum ,
yes splishsplash 2.4 is installed
 i managed to solve the problem and i now have the  msgpack.zst files under the our_default_data/valid and our_default_data/train folders 
i'm however running into another issue when running ./train_network_tf.py from the scripts folder : 
File "./../datasets/dataset_reader_physics.py", line 45, in __iter__
    box = data[0]['box']
IndexError: list index out of range

**Comment by benjaminum** [comment]
Did you solve this problem?

**Comment by raynehe** [comment]
@GUT2060 Hi, sorry to bother you. I'm runnig into the same problem, and I'm wondering if you could tell me how did you solve the problem "*.msgpack.zst': No such file or directory "?
Many thanks!
