### ISSUE TITLE
Can you provide the dam break data used in your work?

### ISSUE THREAD

**Issue by JinxVision** [intel-isl/DeepLagrangianFluids#18]
Hi, I try to run your model on the dam break data mentioned in your paper. Could you please provide the data used in your work, or the generation code/settings?

**Comment by benjaminum** [comment]
Hi, the data was generated with the code from DPI-Net. I can provide the data but it will take some time to convert.

**Comment by JinxVision** [comment]
Thank you for your reply！ How long will it take to convert this data？

**Comment by benjaminum** [comment]
Sometime next week should be possible.

**Comment by JinxVision** [comment]
Thanks a lot! Looking forward to your data.
Moreover, I notice that the data('our data 6k particles') you used in Table 1 of the paper is different form the data used in Table 5. It seems that the data used in Table 2 and Table 5 is the same as the data you provided in this project. So can you also provide this version of the data('our data 6k particles')?

**Comment by benjaminum** [comment]
Yes

**Comment by JinxVision** [comment]
I'm sorry to bother you. Can you provide the DPI data and 'our data 6k particles' used in the paper now?

**Comment by benjaminum** [comment]
Hi, please have a look at the latest commit and the config file ```dambreak.yaml```.

**Comment by JinxVision** [comment]
Thanks very much! That helped me a lot!
