### ISSUE TITLE
Please set the path to the DynamicBoundarySimulator in

### ISSUE THREAD

**Issue by weiwenying** [intel-isl/DeepLagrangianFluids#20]
when run:
```bash
cd datasets
./create_data.sh
```

It's raise:

```bash
Traceback (most recent call last):
  File "create_physics_scenes.py", line 22, in <module>
    from splishsplash_config import SIMULATOR_BIN, VOLUME_SAMPLING_BIN
  File "/home/weiwenying/projects/tests/DeepLagrangianFluids/datasets/splishsplash_config.py", line 6, in <module>
    raise ValueError(
ValueError: Please set the path to the DynamicBoundarySimulator in /home/weiwenying/projects/tests/DeepLagrangianFluids/datasets/splishsplash_config.py
```

where DynamicBoundarySimulator? How to get it? Thanks!

**Comment by benjaminum** [comment]
This is part of SPlisHSPlasH https://github.com/InteractiveComputerGraphics/SPlisHSPlasH 
Make sure that you use version 2.4.0.

**Comment by benjaminum** [comment]
I hope the comment above helped. Please reopen the issue if there is still a problem.

**Comment by ljj0831** [comment]
You have said in the code "Config file that stores the paths to the SPlisHSPlasH binaries ", but I could not find the DynamicBoundarySimulator binary and the VolumeSampling binary in SPlisHSPlasH-2.4.0.  There are only some dirs named DynamicBoundarySimulator and VolumeSampling . How to get them? Thanks!
