### ISSUE TITLE
pyopenvdb module

### ISSUE THREAD

**Issue by ytimber** [intel-isl/DeepLagrangianFluids#21]
Hi, 

I'm currently trying to use ```scripts/create_surface_meshes.py```, but it asks for pyopenvdb. I'm wondering which version I should be downloading.
When I used ```python3 -m pip install pyopenvdb```, it generates the following error 
```
ERROR: Could not find a version that satisfies the requirement pyopenvdb
ERROR: No matching distribution found for pyopenvdb
```
Any insight on how this can be done is immensely appreciated!

**Comment by benjaminum** [comment]
I compiled the python module for OpenVDB from source https://github.com/AcademySoftwareFoundation/openvdb

**Comment by syguan96** [comment]
Hi @benjaminum, could you please tell me the version of OpenVDB you used.

**Comment by benjaminum** [comment]
I used version 7.0

**Comment by ytimber** [comment]
@benjaminum Thanks! I ran into the following issue while running the ```create_surface_meshes.py```
```
free(): invalid pointer
```
have you also encountered this error while running your code? I'm wondering whether you might provide me with some insights on why this is happening. Many thanks in advance! :))

EDIT:
solved! Just simply load pyopenvdb as the first module rather than the last.

**Comment by syguan96** [comment]
I use conda to create an environment. Then build openvdb with `OPENVDB_BUILD_PYTHON_MODULE=ON`. But after `make install`, I met the problem: `ModuleNotFoundError: No module named 'pyopenvdb'`. 

@ytimber, could you please tell me your install procedure?

**Comment by ytimber** [comment]
@syguan96 
Hi, I didn't compile from source. I used ```python3.7 -m pip install pyopenvdb```

**Comment by benjaminum** [comment]
Thanks @ytimber @syguan96 for the comments and hints. Please reopen if there is still an issue.
