### ISSUE TITLE
Visualizing Bounding Box Simulation in Blender

### ISSUE THREAD

**Issue by arjun-mani** [intel-isl/DeepLagrangianFluids#24]
Hello,

Thanks for open-sourcing the code for this great paper! I'm exploring this field of learning particle-based fluid simulation, and I was looking to your codebase for how to visualize simulations. It seems the workflow involves importing a .blend file into Blender and using the blender_external_mesh.py file to load particle data. 

The dataset I'm working with involves fluid simulation in bounding box containers. Is it possible for you to provide bounding_boxes.blend? I see the canyon blend file, but 'bounding_boxes.blend' is referenced in the obj files but not provided. I would really appreciate it. In addition, if you could provide any guidance on how to create such a blend file for known bounding box coordinates, that would be extremely helpful! (as I am very new to Blender). Thanks very much, I look forward to hearing from you.

**Comment by benjaminum** [comment]
Please have a look at the latest commit and scenes/boxes_render.blend

**Comment by arjun-mani** [comment]
Thanks very much, I really appreciate it!
