### ISSUE TITLE
A question about network's output

### ISSUE THREAD

**Issue by alex-wy** [intel-isl/DeepLagrangianFluids#5]
I have read ur paper. It's really an excellent work.
But I'm a little confused about why its output should be divided by "128" in the end.

That's the sentence which mentions it in paper.
> The output of the network is scaled with 1/128 to roughly adjust the output range to the ground truth position correction of the training data.

Hope u can answer my question. Thx!

**Comment by benjaminum** [comment]
The purpose of the factor is to make the network output range and the training data range more compatible such that the training does not need to deal with this difference in scale.
It is an artifact of how we set up the networks. As an alternative we could change the initialization of the network weights and get rid of this factor.
Hope this helps!
