### ISSUE TITLE
Can you provide your generated data?

### ISSUE THREAD

**Issue by JinxVision** [intel-isl/DeepLagrangianFluids#6]
It takes so long for me to generate data. I will be very grateful if you can provide the generated data.

**Comment by benjaminum** [comment]
Hi, please have a look at the latest commit. It adds a download link to the readme. Let me know if there are problems.

**Comment by JinxVision** [comment]
Thank you ver much. I can download it.

**Comment by JinxVision** [comment]
Sorry. I cannot download it. What is wrong with it?
![image](https://user-images.githubusercontent.com/24996629/83851213-9a814800-a744-11ea-8d1c-5475948cc282.png)

**Comment by benjaminum** [comment]
Hi, can you try again now? We had to change the link due to some technical problem. The new link should now have the right permissions.

**Comment by benjaminum** [comment]
The link should work now. Please reopen if you encounter problems with the download.
