### ISSUE TITLE
[Question] Open3D with ML module -> Building Tensorflow ops on Windows is currently not supported.

### ISSUE THREAD

**Issue by FlorentGuinier** [intel-isl/DeepLagrangianFluids#7]
Hey not directly related to your repo, however you might know the answers :

When compiling open3d with ML module on windows (with BUILD_GLFW=ON to avoid problen with GLFW lib) I got the following error:

$ cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TENSORFLOW_OPS=ON -DBUILD_CUDA_MODULE=ON -DBUILD_GLFW=ON
-- New GUI is currently unsupported on Windows
<...>
-- Building library 3rdparty_poisson from source
CMake Error at src/Open3D/ML/CMakeLists.txt:2 (message):
`  Building Tensorflow ops on Windows is currently not supported.`

That seems unexpected. Do you guys have an hint on what could be happening here?

Thanks!

Florent

**Comment by benjaminum** [comment]
Thanks for your question. It is more specific to Open3D so I answered here https://github.com/intel-isl/Open3D/issues/1973

**Comment by FlorentGuinier** [comment]
Thanks for the answer and follow up on Open3D forum, closing.
