### ISSUE TITLE
Will you provide a pytorch version continuous conv?

### ISSUE THREAD

**Issue by hzaskywalker** [intel-isl/DeepLagrangianFluids#8]
Thanks for the great work! I am amazed by the efficiency of Continuous Convolutions as described in the paper and hope that I can use it in pytorch. I see a pytorch folder in open3d.ml. Does this mean you will port CConv to pytorch soon?

**Comment by benjaminum** [comment]
Yes, we are working on a pytorch version but it will take some weeks.

**Comment by benjaminum** [comment]
@hzaskywalker  The pytorch ops and layers are finally in the Open3D master branch. I will add scripts for training and inference with pytorch to this repo soon.
