### ISSUE TITLE
Open3D/3rdparty/fmt/include/fmt/core.h(477): error: identifier "parse_context" is undefined

### ISSUE THREAD

**Issue by lij131** [intel-isl/DeepLagrangianFluids#9]
After I run the code in the "Building Open3D with ML module" to install Open3d ML module:
`git clone --recursive --branch ml-module https://github.com/intel-isl/Open3D.git`
`mkdir Open3D/build`
`cd Open3D/build`

`cmake .. -DBUILD_EIGEN3=ON -DBUILD_GLEW=ON  -DBUILD_JSONCPP=ON    -DBUILD_PNG=ON  -DCMAKE_BUILD_TYPE=Release -DBUILD_TENSORFLOW_OPS=ON -DBUILD_CUDA_MODULE=ON`
`make install-pip-package`
after I `make install-pip-package` ，I got an MAKE Error
`[ 91%] Linking CXX shared module ../../lib/Release/Python/pybind.cpython-37m-x86_64-linux-gnu.so`
`[ 91%] Built target pybind`
`Scanning dependencies of target open3d_tf_ops`
`[ 91%] Building CUDA object src/Open3D/ML/TensorFlow/CMakeFiles/open3d_tf_ops.dir/__/ContinuousConv/Detail/ContinuousConvCUDAKernels.cu.o`
`[ 91%] Building CXX object src/Open3D/ML/TensorFlow/CMakeFiles/open3d_tf_ops.dir/ContinuousConv/ContinuousConvBackpropFilterOpKernel.cpp.o`
`[ 91%] Building CUDA object src/Open3D/ML/TensorFlow/CMakeFiles/open3d_tf_ops.dir/ContinuousConv/ContinuousConvBackpropFilterOpKernel.cu.o`
`/home/es2/anaconda3/lib/python3.7/site-packages/tensorflow/include/Eigen/src/Core/util/XprHelper.h(114): warning: __host__ annotation is ignored on a function("no_assignment_operator") that is explicitly defaulted on its first declaration`

`/home/es2/anaconda3/lib/python3.7/site-packages/tensorflow/include/Eigen/src/Core/util/XprHelper.h(114): warning: __device__ annotation is ignored on a function("no_assignment_operator") that is explicitly defaulted on its first declaration`

`/home/es2/anaconda3/lib/python3.7/site-packages/tensorflow/include/Eigen/src/Core/util/XprHelper.h(115): warning: __host__ annotation is ignored on a function("no_assignment_operator") that is explicitly defaulted on its first declaration`
`/home/es2/Open3D/3rdparty/fmt/include/fmt/core.h(477): error: identifier "parse_context" is undefined`

`/home/es2/Open3D/3rdparty/fmt/include/fmt/core.h(477): error: expected a ";"`

`/home/es2/Open3D/3rdparty/fmt/include/fmt/core.h(478): error: identifier "wparse_context" is undefined`
`/home/es2/Open3D/3rdparty/fmt/include/fmt/core.h(478): error: expected a ";"`

`/home/es2/Open3D/3rdparty/fmt/include/fmt/format.h(2599): error: identifier "writer" is undefined`

`/home/es2/Open3D/3rdparty/fmt/include/fmt/format.h(2599): error: expected a ";"`

`/home/es2/Open3D/3rdparty/fmt/include/fmt/format.h(2600): error: identifier "wwriter" is undefined`

`/home/es2/Open3D/3rdparty/fmt/include/fmt/format.h(2600): error: expected a ";"`

`8 errors detected in the compilation of "/tmp/tmpxft_00003f1d_00000000-6_ContinuousConvBackpropFilterOpKernel.cpp1.ii".
src/Open3D/ML/TensorFlow/CMakeFiles/open3d_tf_ops.dir/build.make:108: recipe for target 'src/Open3D/ML/TensorFlow/CMakeFiles/open3d_tf_ops.dir/ContinuousConv/ContinuousConvBackpropFilterOpKernel.cu.o' failed`
`make[3]: *** [src/Open3D/ML/TensorFlow/CMakeFiles/open3d_tf_ops.dir/ContinuousConv/ContinuousConvBackpropFilterOpKernel.cu.o] Error 1`
`CMakeFiles/Makefile2:1584: recipe for target 'src/Open3D/ML/TensorFlow/CMakeFiles/open3d_tf_ops.dir/all' failed`
`make[2]: *** [src/Open3D/ML/TensorFlow/CMakeFiles/open3d_tf_ops.dir/all] Error 2`
`CMakeFiles/Makefile2:1977: recipe for target 'src/pybind/CMakeFiles/install-pip-package.dir/rule' failed`
`make[1]: *** [src/pybind/CMakeFiles/install-pip-package.dir/rule] Error 2`
`Makefile:691: recipe for target 'install-pip-package' failed`
`make: *** [install-pip-package] Error 2`

How can I fix it?

**Comment by benjaminum** [comment]
Can you provide more information? OS, CUDA, CMake and Tensorflow versions.

**Comment by lij131** [comment]
OS: Ubuntu 18.04
CUDA 10.0.130
CMAKE 3.18.0-rc1
Tensorflow 2.2.0

**Comment by benjaminum** [comment]
Could there be a conflict of the included files for fmtlib? Do you have fmtlib headers installed?

**Comment by lij131** [comment]
> Could there be a conflict of the included files for fmtlib? Do you have fmtlib headers installed?

I got the 'fmt' folder through  the git command:
`git clone --recursive --branch ml-module https://github.com/intel-isl/Open3D.git`
And I haven't used fmt before.

**Comment by benjaminum** [comment]
Can you post the compile command that fails with ```make VERBOSE=1``` ?

**Comment by lij131** [comment]
> Can you post the compile command that fails with `make VERBOSE=1` ?

When I use command `make VERBOSE=1`, It seems have the totally same error as `make install-pip-package`. 
```
[ 68%] Building CUDA object src/Open3D/ML/TensorFlow/CMakeFiles/open3d_tf_ops.dir/ContinuousConv/ContinuousConvBackpropFilterOpKernel.cu.o
cd /home/es2/Downloads/lagrangian_fluid/Open3D/build/src/Open3D/ML/TensorFlow && /usr/local/cuda-10.0/bin/nvcc  -DBUILD_CUDA_MODULE -DFMT_HEADER_ONLY=1 -D_GLIBCXX_USE_CXX11_ABI=0 -Dopen3d_tf_ops_EXPORTS -isystem=/home/es2/Downloads/lagrangian_fluid/Open3D/3rdparty/cub -isystem=/home/es2/Downloads/lagrangian_fluid/Open3D/3rdparty/cutlass -isystem=/home/es2/Downloads/lagrangian_fluid/Open3D/src -isystem=/home/es2/anaconda3/lib/python3.7/site-packages/tensorflow/include -isystem=/home/es2/Downloads/lagrangian_fluid/Open3D/3rdparty/nanoflann/include -isystem=/home/es2/Downloads/lagrangian_fluid/Open3D/3rdparty/parallelstl/include -isystem=/home/es2/Downloads/lagrangian_fluid/Open3D/3rdparty/fmt/include -O3 -DNDEBUG -Xcompiler=-fPIC --compiler-options -Wall --compiler-options -Werror --Werror cross-execution-space-call,reorder,deprecated-declarations -std=c++11 -x cu -c /home/es2/Downloads/lagrangian_fluid/Open3D/src/Open3D/ML/TensorFlow/ContinuousConv/ContinuousConvBackpropFilterOpKernel.cu -o CMakeFiles/open3d_tf_ops.dir/ContinuousConv/ContinuousConvBackpropFilterOpKernel.cu.o
/home/es2/anaconda3/lib/python3.7/site-packages/tensorflow/include/Eigen/src/Core/util/XprHelper.h(114): warning: __host__ annotation is ignored on a function("no_assignment_operator") that is explicitly defaulted on its first declaration

/home/es2/anaconda3/lib/python3.7/site-packages/tensorflow/include/Eigen/src/Core/util/XprHelper.h(114): warning: __device__ annotation is ignored on a function("no_assignment_operator") that is explicitly defaulted on its first declaration


/home/es2/anaconda3/lib/python3.7/site-packages/tensorflow/include/Eigen/src/Core/ArrayWrapper.h(47): warning: __host__ annotation is ignored on a function("ArrayWrapper") that is explicitly defaulted on its first declaration

/home/es2/anaconda3/lib/python3.7/site-packages/tensorflow/include/Eigen/src/Core/ArrayWrapper.h(47): warning: __device__ annotation is ignored on a function("ArrayWrapper") that is explicitly defaulted on its first declaration

/home/es2/anaconda3/lib/python3.7/site-packages/tensorflow/include/Eigen/src/Core/ArrayWrapper.h(145): warning: __host__ annotation is ignored on a function("MatrixWrapper") that is explicitly defaulted on its first declaration

/home/es2/anaconda3/lib/python3.7/site-packages/tensorflow/include/Eigen/src/Core/ArrayWrapper.h(145): warning: __device__ annotation is ignored on a function("MatrixWrapper") that is explicitly defaulted on its first declaration

/home/es2/Downloads/lagrangian_fluid/Open3D/3rdparty/fmt/include/fmt/core.h(477): error: identifier "parse_context" is undefined

/home/es2/Downloads/lagrangian_fluid/Open3D/3rdparty/fmt/include/fmt/core.h(477): error: expected a ";"

/home/es2/Downloads/lagrangian_fluid/Open3D/3rdparty/fmt/include/fmt/core.h(478): error: identifier "wparse_context" is undefined

/home/es2/Downloads/lagrangian_fluid/Open3D/3rdparty/fmt/include/fmt/core.h(478): error: expected a ";"

/home/es2/Downloads/lagrangian_fluid/Open3D/3rdparty/fmt/include/fmt/format.h(2599): error: identifier "writer" is undefined

/home/es2/Downloads/lagrangian_fluid/Open3D/3rdparty/fmt/include/fmt/format.h(2599): error: expected a ";"

/home/es2/Downloads/lagrangian_fluid/Open3D/3rdparty/fmt/include/fmt/format.h(2600): error: identifier "wwriter" is undefined

/home/es2/Downloads/lagrangian_fluid/Open3D/3rdparty/fmt/include/fmt/format.h(2600): error: expected a ";"

8 errors detected in the compilation of "/tmp/tmpxft_00006376_00000000-6_ContinuousConvBackpropFilterOpKernel.cpp1.ii".
src/Open3D/ML/TensorFlow/CMakeFiles/open3d_tf_ops.dir/build.make:108: recipe for target 'src/Open3D/ML/TensorFlow/CMakeFiles/open3d_tf_ops.dir/ContinuousConv/ContinuousConvBackpropFilterOpKernel.cu.o' failed
make[2]: *** [src/Open3D/ML/TensorFlow/CMakeFiles/open3d_tf_ops.dir/ContinuousConv/ContinuousConvBackpropFilterOpKernel.cu.o] Error 1
make[2]: Leaving directory '/home/lj2/Downloads/lagrangian_fluid/Open3D/build'
CMakeFiles/Makefile2:1585: recipe for target 'src/Open3D/ML/TensorFlow/CMakeFiles/open3d_tf_ops.dir/all' failed
make[1]: *** [src/Open3D/ML/TensorFlow/CMakeFiles/open3d_tf_ops.dir/all] Error 2
make[1]: Leaving directory '/home/lj2/Downloads/lagrangian_fluid/Open3D/build'
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by benjaminum** [comment]
The compile command seems fine. Can you try to upgrade to CUDA 10.1 and see if that helps?

**Comment by benjaminum** [comment]
There have been many changes to Open3D in the last days. Please open this issue again if you still have problems.
